---
extends: default
ignore: |
    .nox/
rules:
  line-length:
    max: 120
  quoted-strings:
    quote-type: single
    required: only-when-needed
  truthy:
    allowed-values: ['true', 'false', 'on']
